services:

  optixmovies.api:
    image: ${DOCKER_REGISTRY-}optixmoviesapi
    build:
      context: .
      dockerfile: src/OptixMovies.API/Dockerfile
    depends_on: 
      - optixmovies.cosmos

  # optixmovies.gateway:
  #   image: ${DOCKER_REGISTRY-}optixmoviesgateway
  #   build:
  #     context: .
  #     dockerfile: src/OptixMovies.Gateway/Dockerfile

  optixmovies.cosmos:
    container_name: OptixMovies.Cosmos
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    ports:
      - "8081:8081"
      - "8900:8900"

  # optixmovies.storage:
  #   container_name: OptixMovies.Storage
  #   image: mcr.microsoft.com/azure-storage/azurite:latest
  #   volumes:
  #     - azurite:/data
  #   ports:
  #     - "10000-10002:10000-10002"

volumes:
  azurite: