services:

  optixmovies.api:
    image: ${DOCKER_REGISTRY-}optixmoviesapi
    build:
      context: .
      dockerfile: src/OptixMovies.API/Dockerfile

  optixmovies.gateway:
    image: ${DOCKER_REGISTRY-}optixmoviesgateway
    build:
      context: .
      dockerfile: src/OptixMovies.Gateway/Dockerfile

  optixmovies.cosmos:
    container_name: optixmovies-cosmos
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    ports:
      - "8081:8081"
      - "8900:8900"